version: "3"
services:
  nextjs-ui:
    build:
      context: ./client
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    container_name: nextjs-ui
    command: yarn dev:client
    stdin_open: true
    working_dir: /app