name: docker-compose-actions-workflow

on: push

defaults:
  run:
    working-directory: ./client

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

  client-dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

  client-linter:
    needs: [setup, client-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore cached Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Run Linter
        working-directory: ./client
        run: yarn lint

  client-build:
    needs: [setup, client-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore cached Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Client build
        run: yarn build

#  client-lighthouse:
#    needs: [client-dependencies, client-build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run Lighthouse CI
#        run: |
#            yarn global add @lhci/cli@0.3.x
#            lhci autorun
#        env:
#          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  docker-run:
    needs: client-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: yarn dev:up
