name: docker-compose-actions-workflow

on: push


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

  client-dependencies:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn install  

  client-build:
    needs: client-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ./client/.next
          key: build-${{ hashFiles('**/client/**/src/**') }}

      - name: Client build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: yarn build

  client-linter:
    needs: client-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Run Linter
        run: yarn lint

#  docker-run:
#    needs: client-dependencies
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build the stack
#        run: yarn dev:up
